# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b564537a250be6b8b84bd0635d6c92803f04e7e57bebef67813b83190b29caf8fa29f745c6522b894b628aa50357a0d8b12ceff5e1b6f948772b8841ea0c07

test:
  secret_key_base: 9d329be2b5700af9f9c14dddf236d7a91ac9fe986c8705570b39b7e39899986c5fc552228453f4f9ad94ce5e371367296d42d8a9afef827f0385359273c82bfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
